Update SpatialEpigenome.rst
atlasxomics/AtlasXpipeline_docs pull request #5
Opened 2023-03-03 21:24 UTC by tamarajafar

updates.

2023-03-07 16:53 UTC, poorvi4 commented on docs/SpatialEpigenome.rst
> +It's important to understand how gene expression varies across different cell types or clusters. The addGroupCoverages function calculates the average coverage of each genomic region (or "peak") in t
This function is more so for creating pseudo-bulk replicates to account for binary nature of single cell ATAC data and to prepare our data for peak-calling. In ATAC data, we dont have gene expression data however we do have gene score information which attempts to assigns an accessibility "score" to each gene according to the number of peaks near its TSS

2023-03-07 17:19 UTC, poorvi4 commented on docs/SpatialEpigenome.rst
> +It's also important to identify genomic regions that are consistently expressed across multiple samples. These are called "peaks" and can be identified using software like MACS2. The addReproducibleP
Better to specify **accessible** genomic regions. Also, change "The addReproduciblepeakSet function to ..." to  "We call the addReproduciblePeakSet function to ..."

2023-03-07 17:42 UTC, poorvi4 requested changes
Please make the requested changes as given in the review comments.

2023-03-07 17:42 UTC, poorvi4 commented on docs/SpatialEpigenome.rst
> +Check if motif annotations are already present in the project. If not, use the addMotifAnnotations function to add them to the ArchR project. The motif set used will depend on the data species. If th
You can get rid of the if-else code block and just keep the line of code to add motif annotations

2023-03-07 17:42 UTC, poorvi4 commented on docs/SpatialEpigenome.rst
> +Use the addDeviationsMatrix() function to add a matrix of deviations to the ArchRProj object. The peakAnnotation argument specifies the name of the peak annotations to use when calculating the deviat
Change "add a matrix of deviations" to "add a matrix of per-cell deviations "

2023-03-07 17:42 UTC, poorvi4 commented on docs/SpatialEpigenome.rst
> +Compute deviation scores for the motifs of interest using the getDeviation_ArchR() function. The function takes the ArchR project object, the list of motifs, and the imputed weights computed with get
This functions gets the deviation  scorematrix from the archR project. Deviation scores are computed before.

2023-03-07 17:42 UTC, poorvi4 commented on docs/SpatialEpigenome.rst
> +Create individual motif plots by by generating a list of ggplot objects for each motif plot. It iterates over the row names of spatial.obj, extracts the motif PWM for each row, and converts it to a p
You can get rid of this code block/section which. computes the seqlogos plots (these are not motif plots)

2023-03-07 17:42 UTC, poorvi4 commented on docs/SpatialEpigenome.rst
> +It's important to understand how gene expression varies across different cell types or clusters. The addGroupCoverages function calculates the average coverage of each genomic region (or "peak") in t
This function is more so for creating pseudo-bulk replicates to account for binary nature of single cell ATAC data and to prepare our data for peak-calling. It also helps with determining how reproducible peak calling is in the next step.In ATAC data, we dont have gene expression data however we do have gene score information which attempts to assigns an accessibility "score" to each gene according to the number of peaks near its TSS

2023-03-07 22:18 UTC, tamarajafar commented
final review needed to merge! added requests

2023-03-08 16:36 UTC, poorvi4 requested changes
See comments.

2023-03-08 16:36 UTC, poorvi4 commented on docs/SpatialEpigenome.rst
> +
Please delete the ggseqlogo section. This section is used to create the seqlogo plots which are different from the motif plots. Also the image to show the respective marker motifs are missing from this commit however were found in previous merges.

2023-03-14 16:39 UTC, poorvi4 approved these changes

2023-03-14 16:39 UTC, merged